version: "3.8"


services:

  django_app:
    build: ./
    container_name: prime_container
    working_dir: /prime
    restart: always
    command: ./commands/run_server_${MODE}.bash
    volumes:
      - ./admins:/prime/admins
      - ./commands:/prime/commands
      - media_content:/var/www/prime/media
      - ./prime:/prime/prime
      - static_content:/var/www/prime/static
      - ./templates:/prime/templates
      - ./users:/prime/users
      - ./config.py:/prime/config.py
      - ./manage.py:/prime/manage.py
    ports:
      - "${PORT}:${WSGI_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres:14.1
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5000:80"
    depends_on:
      - postgres


  nginx:
    image: nginx:1.21.5
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/var/www/prime/static
      - media_content:/var/www/prime/media
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - django_app


volumes:
  pg_data: { }
  static_content: { }
  media_content: { }